FROM mcr.microsoft.com/playwright/python:v1.40.0-jammy

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN playwright install chromium

COPY . .

CMD ["uvicorn", "get_place_by_title_and_category:app", "--host", "0.0.0.0", "--port", "8000"]
